apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    app: nodejs-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4444
      protocol: TCP
  selector:
    app: nodejs-app
